---
- name: Install Extra Packages for Enterprise Linux (EPEL) repo.
  package: name=epel-release state=present
  when: ansible_os_family == 'RedHat'

- name: Install OS dependencies (RedHat).
  package: name={{ item }} state=present
  with_items:
    - gcc
    - gcc-c++
    - libibverbs-devel
    - libselinux-python
    - Lmod
    - openssl-devel
    - patch
    - perl
    - git
    - unzip
    - libX11-devel
    - libXrender-devel
    - libXext-devel
    - mesa-libGL-devel
    - mesa-libGLU-devel
    - libXext-devel
    - libXt-devel
  when: ansible_os_family == 'RedHat'

- name: Patch Lmod profile
  lineinfile:
    dest: /usr/share/lmod/lmod/init/profile
    state: present
    regexp: '^\s+my_shell=.+/ps\s.+ocomm'
    line: '  my_shell=$(/bin/ps -p $$ -ocomm=)'

- name: Add easybuild group
  group: name=easybuild state=present

- name: Add easybuild user
  user: name=easybuild
        group=easybuild
        shell=/bin/bash
        state=present

- name: Create EasyBuild directories
  file: path={{ easybuild_root }}/{{ item }} owner=easybuild group=easybuild mode='u=rwx,g=rwx,o=rx' state=directory
  with_items:
    - ''
    - custom
    - modules
    - modules/.lmod
    - software
    - sources

- name: Configure Lmod and EasyBuild
  template: src={{ item.src }} dest={{ easybuild_root }}/modules/{{ item.dest}} owner=easybuild group=easybuild mode='u=rw,g=rw,o=r'
  with_items:
    - src: lmodrc.lua
      dest: .lmod/lmodrc.lua
    - src: modules.admin
      dest: modules.admin
    - src: modules.bashrc
      dest: modules.bashrc

- name: Add Lmod configuration to /etc/profile.d/
  template: src=easybuild.sh dest=/etc/profile.d/z01_easybuild.sh

- name: Fetch EasyBuild bootstrap script
  get_url:
    url: https://raw.githubusercontent.com/hpcugent/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py
    dest: '{{ easybuild_root }}/custom/bootstrap_eb.py'
  become_user: easybuild

# Ansible doesn't run task in a login shell, so we have to source the
# EasyBuild config manually. We might want to create some abstraction for
# this.
- name: Install EasyBuild using bootstrap script
  shell: . {{ easybuild_root }}/modules/modules.bashrc && umask 0002 && python {{ easybuild_root }}/custom/bootstrap_eb.py ${HPC_ENV_PREFIX}
  args:
    creates: '{{ easybuild_root }}/software/EasyBuild'
  become_user: easybuild
